server:
  context-path: /consumer
  port: 9000
spring:
  application:
    name: user-consumer
  cloud:
    consul:
      host: 10.48.114.61
      port: 8500
      discovery:
        register: false
feign:
  hystrix:
    enabled: true