server:
  port: 9003
spring:
  application:
    name: user-service
  cloud:
    consul:
      host: 10.48.114.61
      port: 8500
      discovery:
        healthCheckPath: /health
        healthCheckInterval: 10s